export const COUNTRY_ISO_MAP: Record<string, string> = {
  "Argentina": "ar",
  "France": "fr",
  "Brazil": "br",
  "Germany": "de",
  "England": "gb-eng",
  "Spain": "es",
  "Italy": "it",
  "Portugal": "pt",
  "Netherlands": "nl",
  "Belgium": "be",
  "Croatia": "hr",
  "Uruguay": "uy",
  "Morocco": "ma",
  "Colombia": "co",
  "USA": "us",
  "Mexico": "mx",
  "Senegal": "sn",
  "Japan": "jp",
  "South Korea": "kr",
  "Switzerland": "ch",
  "Denmark": "dk",
  "Sweden": "se",
  "Poland": "pl",
  "Wales": "gb-wls",
  "Serbia": "rs",
  "Ecuador": "ec",
  "Cameroon": "cm",
  "Canada": "ca",
  "Ghana": "gh",
  "Australia": "au",
  "Costa Rica": "cr",
  "Tunisia": "tn",
  "Saudi Arabia": "sa",
  "Iran": "ir",
  "Qatar": "qa",
  "Peru": "pe",
  "Chile": "cl",
  "Egypt": "eg",
  "Nigeria": "ng",
  "Algeria": "dz",
  "Ivory Coast": "ci",
  "Mali": "ml",
  "South Africa": "za",
  "New Zealand": "nz"
};

export function getCountryIsoCode(countryName: string): string {
  return COUNTRY_ISO_MAP[countryName] || "un"; // 'un' for United Nations / default
}
